// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WWjMTrQTbToZdP8u5SqIxy-0fnPFtg8',
    appId: '1:738574600102:web:e345bbe7ef587820277167',
    messagingSenderId: '738574600102',
    projectId: 'customer-a952f',
    authDomain: 'customer-a952f.firebaseapp.com',
    storageBucket: 'customer-a952f.firebasestorage.app',
    measurementId: 'G-FBQYN691J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vtQEJg3E08eExYoCCzrvLS1O2Mila3s',
    appId: '1:738574600102:android:068bf8a2cea2a1c8277167',
    messagingSenderId: '738574600102',
    projectId: 'customer-a952f',
    storageBucket: 'customer-a952f.firebasestorage.app',
  );
}
